server:
  port: 8888

#yml格式的配置文件
spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://118.178.89.86:3306/wuye05?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    password: "!Mysql2020"
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filter: stat

  #配置视图解析器
  mvc:

  #配置时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#配置mybatis
mybatis:
  type-aliases-package: wuye.xyq.pojo
  #指定mybatis映射文件所在的位置
  mapper-locations: classpath*:mapper/*.xml
#  basePackage: com.study.model.mdao


logging:
  level:
    # 在控制台输出mybatis的mapper接口执行的SQL语句以及影响的行数
    com:
      # crmxyq:
      model:
        mdao: debug
        # 打印JPA的语句以及每次传递的参数信息
    org:
      springframework:
        security:
          - debug
          - info
        web: error
      hibernate:
        SQL: debug
        engine:
          QueryParameters: debug
          query:
            HQLQueryPlan: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace