
server:
  port: 6666
spring:

  datasource:
    url: jdbc:mysql://118.178.89.86:3306/crm?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    password: "!Mysql2020"
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filter: stat
  mvc:


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis:
  type-aliases-package: wuye.xyq.pojo
  mapper-locations: classpath*:mapper/*.xml


logging:
  level:
    com:
      model:
        mdao: debug
    org:
      springframework:
        security:
          - debug
          - info
        web: error
      hibernate:
        SQL: debug
        engine:
          QueryParameters: debug
          query:
            HQLQueryPlan: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
